import img_mercedes_a200 from "../assets/images/mercedes_a200.svg";
import img_bmw from "../assets/images/bmw.svg";
import img_captur from "../assets/images/captur.svg";
import img_cruze from "../assets/images/cruze.svg";
import img_ford_expedition from "../assets/images/ford_expedition.svg";
import img_ka from "../assets/images/ka.svg";
import img_kicks from "../assets/images/kicks.svg";
import img_mercedes from "../assets/images/mercedes.svg";
import img_mercedes2 from "../assets/images/mercedes2.svg";
import img_moto1 from "../assets/images/moto1.svg";
import img_moto2 from "../assets/images/moto2.svg";
import img_moto3 from "../assets/images/moto3.svg";
import img_moto4 from "../assets/images/moto4.svg";
import img_moto5 from "../assets/images/moto5.svg";
import img_moto6 from "../assets/images/moto6.svg";
import img_moto7 from "../assets/images/moto7.svg";
import img_mustang from "../assets/images/mustang.svg";
import img_porche from "../assets/images/porche.svg";
import img_quadriciculo from "../assets/images/quadriciculo.svg";

export const vehicles = [
  {
    id: '1',
    name: "Mercedes Benz A200 CGI",
    info: "Tração dianteira. Direção elétrica, 6 marchas, transmissão manual, motor de combustão interna, Velocidade máxima: 225km/h, Potência 163cv, Combustível: Gasolina",
    owner: "Mazuquiebe",
    owner_initials: "M",
    year: "2013",
    km: "0",
    price: "78.500,00",
    time_auction: "2:00:00",
    img: [`${img_mercedes_a200}`],
    category: "car",
  },
  {
    id: '2',
    name: "BMW M8",
    info: "Tração dianteira. Direção elétrica, 6 marchas, transmissão manual, motor de combustão interna, Velocidade máxima: 225km/h, Potência 163cv, Combustível: Gasolina",
    owner: "Emerson Gonçalves",
    owner_initials: "EG",
    year: "2020",
    km: "0",
    price: "180.000,00",
    time_auction: "2:00:00",
    img: [`${img_bmw}`],
    category: "car",
  },
  {
    id: '3',
    name: "Renault Captur",
    info: "Tração dianteira. Direção elétrica, 6 marchas, transmissão manual, motor de combustão interna, Velocidade máxima: 225km/h, Potência 163cv, Combustível: Gasolina",
    owner: "Ana Pereira",
    owner_initials: "AP",
    year: "2018",
    km: "100.000",
    price: "68.500,00",
    time_auction: "2:00:00",
    img: [`${img_captur}`],
    category: "car",
  },
  {
    id: '4',
    name: "Chevrolet Cruze",
    info: "Tração dianteira. Direção elétrica, 6 marchas, transmissão manual, motor de combustão interna, Velocidade máxima: 225km/h, Potência 163cv, Combustível: Gasolina",
    owner: "Fernando Henrique",
    owner_initials: "FH",
    year: "2018",
    km: "0",
    price: "60.500,00",
    time_auction: "2:00:00",
    img: [`${img_cruze}`],
    category: "car",
  },
  {
    id: '5',
    name: "Ford Expedition",
    info: "Tração dianteira. Direção elétrica, 6 marchas, transmissão manual, motor de combustão interna, Velocidade máxima: 225km/h, Potência 163cv, Combustível: Gasolina",
    owner: "Mazuquiebe",
    owner_initials: "M",
    year: "2013",
    km: "0",
    price: "78.500,00",
    time_auction: "2:00:00",
    img: [`${img_ford_expedition}`],
    category: "car",
  },
  {
    id: '6',
    name: "Ford Ka",
    info: "Tração dianteira. Direção elétrica, 6 marchas, transmissão manual, motor de combustão interna, Velocidade máxima: 225km/h, Potência 163cv, Combustível: Gasolina",
    owner: "Emerson Gonçalves",
    owner_initials: "EG",
    year: "2013",
    km: "0",
    price: "78.500,00",
    time_auction: "2:00:00",
    img: [`${img_ka}`],
    category: "car",
  },
  {
    id: '7',
    name: "Nissan Kicks",
    info: "Tração dianteira. Direção elétrica, 6 marchas, transmissão manual, motor de combustão interna, Velocidade máxima: 225km/h, Potência 163cv, Combustível: Gasolina",
    owner: "Ana Pereira",
    owner_initials: "AP",
    year: "2013",
    km: "0",
    price: "78.500,00",
    time_auction: "2:00:00",
    img: [`${img_kicks}`],
    category: "car",
  },
  {
    id: '8',
    name: "Mercedes Benz A300",
    info: "Tração dianteira. Direção elétrica, 6 marchas, transmissão manual, motor de combustão interna, Velocidade máxima: 225km/h, Potência 163cv, Combustível: Gasolina",
    owner: "Fernando Henrique",
    owner_initials: "FH",
    year: "2013",
    km: "0",
    price: "78.500,00",
    time_auction: "2:00:00",
    img: [`${img_mercedes}`],
    category: "car",
  },
  {
    id: '9',
    name: "Mercedes Benz A400",
    info: "Tração dianteira. Direção elétrica, 6 marchas, transmissão manual, motor de combustão interna, Velocidade máxima: 225km/h, Potência 163cv, Combustível: Gasolina",
    owner: "Mazuquiebe",
    owner_initials: "M",
    year: "2013",
    km: "0",
    price: "78.500,00",
    time_auction: "2:00:00",
    img: [`${img_mercedes2}`],
    category: "car",
  },
  {
    id: '10',
    name: "Moto1",
    info: "Tração dianteira. Direção elétrica, 6 marchas, transmissão manual, motor de combustão interna, Velocidade máxima: 225km/h, Potência 163cv, Combustível: Gasolina",
    owner: "Emerson Gonçalves",
    owner_initials: "EG",
    year: "2013",
    km: "0",
    price: "78.500,00",
    time_auction: "2:00:00",
    img: [`${img_moto1}`],
    category: "motorcicle",
  },
  {
    id: '11',
    name: "Moto 2",
    info: "Tração dianteira. Direção elétrica, 6 marchas, transmissão manual, motor de combustão interna, Velocidade máxima: 225km/h, Potência 163cv, Combustível: Gasolina",
    owner: "Ana Pereira",
    owner_initials: "AP",
    year: "2013",
    km: "0",
    price: "78.500,00",
    time_auction: "2:00:00",
    img: [`${img_moto2}`],
    category: "motorcicle",
  },
  {
    id: '12',
    name: "Moto3",
    info: "Tração dianteira. Direção elétrica, 6 marchas, transmissão manual, motor de combustão interna, Velocidade máxima: 225km/h, Potência 163cv, Combustível: Gasolina",
    owner: "Fernando Henrique",
    owner_initials: "FH",
    year: "2013",
    km: "0",
    price: "78.500,00",
    time_auction: "2:00:00",
    img: [`${img_moto3}`],
    category: "motorcicle",
  },
  {
    id: '13',
    name: "Moto 4",
    info: "Tração dianteira. Direção elétrica, 6 marchas, transmissão manual, motor de combustão interna, Velocidade máxima: 225km/h, Potência 163cv, Combustível: Gasolina",
    owner: "Mazuquiebe",
    owner_initials: "M",
    year: "2013",
    km: "0",
    price: "78.500,00",
    time_auction: "2:00:00",
    img: [`${img_moto4}`],
    category: "motorcicle",
  },
  {
    id: '14',
    name: "Moto 5",
    info: "Tração dianteira. Direção elétrica, 6 marchas, transmissão manual, motor de combustão interna, Velocidade máxima: 225km/h, Potência 163cv, Combustível: Gasolina",
    owner: "Emerson Gonçalves",
    owner_initials: "EG",
    year: "2013",
    km: "0",
    price: "78.500,00",
    time_auction: "2:00:00",
    img: [`${img_moto5}`],
    category: "motorcicle",
  },
  {
    id: '15',
    name: "Moto 6",
    info: "Tração dianteira. Direção elétrica, 6 marchas, transmissão manual, motor de combustão interna, Velocidade máxima: 225km/h, Potência 163cv, Combustível: Gasolina",
    owner: "Ana Pereira",
    owner_initials: "AP",
    year: "2013",
    km: "0",
    price: "78.500,00",
    time_auction: "2:00:00",
    img: [`${img_moto6}`],
    category: "motorcicle",
  },
  {
    id: '16',
    name: "Moto 7",
    info: "Tração dianteira. Direção elétrica, 6 marchas, transmissão manual, motor de combustão interna, Velocidade máxima: 225km/h, Potência 163cv, Combustível: Gasolina",
    owner: "Fernando Henrique",
    owner_initials: "FH",
    year: "2013",
    km: "0",
    price: "78.500,00",
    time_auction: "2:00:00",
    img: [`${img_moto7}`],
    category: "motorcicle",
  },
  {
    id: '17',
    name: "Mustang",
    info: "Tração dianteira. Direção elétrica, 6 marchas, transmissão manual, motor de combustão interna, Velocidade máxima: 225km/h, Potência 163cv, Combustível: Gasolina",
    owner: "Mazuquiebe",
    owner_initials: "M",
    year: "2013",
    km: "0",
    price: "78.500,00",
    time_auction: "2:00:00",
    img: [`${img_mustang}`],
    category: "car",
  },
  {
    id: '18',
    name: "Porche",
    info: "Tração dianteira. Direção elétrica, 6 marchas, transmissão manual, motor de combustão interna, Velocidade máxima: 225km/h, Potência 163cv, Combustível: Gasolina",
    owner: "Emerson Gonçalves",
    owner_initials: "EG",
    year: "2013",
    km: "0",
    price: "78.500,00",
    time_auction: "2:00:00",
    img: [`${img_porche}`],
    category: "car",
  },
  {
    id: '19',
    name: "Quadriciculo",
    info: "Tração dianteira. Direção elétrica, 6 marchas, transmissão manual, motor de combustão interna, Velocidade máxima: 225km/h, Potência 163cv, Combustível: Gasolina",
    owner: "Ana Pereira",
    owner_initials: "AP",
    year: "2013",
    km: "0",
    price: "78.500,00",
    time_auction: "2:00:00",
    img: [`${img_quadriciculo}`],
    category: "motorcicle",
  },
];
